#!/usr/bin/env ruby
#
name = Dir.pwd.split("/").last.split(".").first
puts name
target = "/rails/app_js/#{name}"

if File.exists?(target)
  puts `git --work-tree #{target} --git-dir #{target}/.git fetch origin && git --work-tree #{target} --git-dir #{target}/.git reset --hard origin/master && chown -R 9999:9999 #{target}`

else
  puts 'Cloning...'
  puts `git clone /var/repos/#{name}.git /rails/app_js/#{name} & chown -R 9999:9999 #{target}`
end
